In [1]:
#Imports


import pandas as pd
from pandas import json_normalize
import requests 
import json
import os
from dotenv import load_dotenv #conda install -c conda-forge python-dotenv
import time
import folium
from folium import Choropleth, Circle, Marker, Icon, Map
from folium.plugins import HeatMap, MarkerCluster
import os
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import numpy as np
from geopy.distance import geodesic as GD

import src.functions as functions

In [2]:
df = pd.read_csv('src/locations_df.csv')

In [3]:
df.rename(columns={"Unnamed: 0": "index"}, inplace=True)

In [4]:
df.drop(columns=["index"],inplace=True)

In [5]:
# f = 100000 + design * 20/87 * 0.1 + tech * 15/87 * 0.1 - starb * 10/87 * 0.1 - airp * 20/87 *0.15 - clubs * 87/87 * 0.1 
#- vegan * 1/87* 0.05 - school * 26/87 * 0.1 - bask* 1/87*0.05 - dog * 0.05*1/87 - cost * 87/87 *0.1 - wage * 87/87 * 0.1

In [6]:
rank = []
for index,row in df.iterrows():
    formula = 10 + row["nº design comp"] * 20/87 * 0.1 + row["nº tech (>$1M)"] * 15/87 * 0.1 - row["dist to starbucks (km)"] * 10/87 * 0.1 - row["dist to airport (km)"] * 20/87 *0.15 - row["average dist to clubs (km)"] * 87/87 * 0.1 - row["average dist to vegan rest. (km)"]*1/87 * 0.05 - row["average dist to schools (km)"] * 26/87 * 0.1 - row["dist. to closes basketball court (km)"]*1/87 *0.05 - row["dist. to closest canine salon (km)"]*1/87 * 0.05 - row["cost living index"] / row["avg_wage"] * 87/87 * 0.2
    rank.append(formula)
rank
        
df["rank"] = rank
df

,name,city,country,latitude,longitude,nº design comp,nº tech (>$1M),dist to starbucks (km),dist to airport (km),average dist to clubs (km),average dist to vegan rest. (km),average dist to schools (km),dist. to closes basketball court (km),dist. to closest canine salon (km),cost living index,avg_wage,rank
0,Lala,Palo Alto,USA,37.451151,-122.154369,6,4,0.729,27.550,4.787222,9.683300,2.134000,1.917,6.491,95.43,6349,8.692617
1,PodTech,Palo Alto,USA,37.408256,-122.154176,6,4,2.312,30.953,10.432143,12.284100,2.422900,3.002,6.842,95.43,6349,7.981631
2,SonicSwap,Palo Alto,USA,37.444487,-122.163979,6,4,0.396,27.437,2.177375,9.110444,1.773333,1.115,5.767,95.43,6349,8.973311
3,MyMiniLife,Palo Alto,USA,37.437328,-122.159928,6,4,1.046,28.251,2.589750,10.697556,1.199333,0.304,6.332,95.43,6349,8.912916
4,Mytopia,Palo Alto,USA,34.007967,-118.489681,6,4,0.357,10.506,4.055222,2.979500,2.051400,0.759,1.982,95.43,6349,9.367395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,BAM Studios,Chicago,USA,41.893622,-87.627423,8,2,0.231,24.437,0.731778,0.989333,0.709700,0.891,0.935,77.35,4777,9.273837
204,Plugola,Chicago,USA,41.907542,-87.662990,8,2,0.540,21.131,1.645100,1.600250,1.271100,0.964,5.169,77.35,4777,9.273349
205,Midway Games,Chicago,USA,41.879535,-87.624333,8,2,0.025,25.302,0.740111,0.807111,0.488400,0.565,1.560,77.35,4777,9.252090
206,Blizzard Entertainment,Irvine,USA,33.669500,-117.822200,1,1,0.743,3.813,3.196300,4.863700,1.819300,0.587,4.248,76.38,6306,9.518211
207,DanceShowoff,Irvine,USA,33.671428,-117.791423,1,1,0.193,6.572,3.419700,5.065500,5.104000,0.413,7.043,76.38,6306,9.307269

In [7]:
df.sort_values(by=['rank'], ascending= False, inplace=True)
df

,name,city,country,latitude,longitude,nº design comp,nº tech (>$1M),dist to starbucks (km),dist to airport (km),average dist to clubs (km),average dist to vegan rest. (km),average dist to schools (km),dist. to closes basketball court (km),dist. to closest canine salon (km),cost living index,avg_wage,rank
112,Unity Technologies,San Francisco,USA,55.692461,12.530107,12,24,2.726,10.072,2.213200,1.152200,1.660700,0.806,0.215,95.43,6349,10.035806
62,Babelgum,London,GBR,53.344104,-6.267494,16,3,0.852,9.321,0.363900,0.532100,0.785700,1.713,0.105,77.87,3497,10.022658
94,Sutros,San Francisco,USA,37.756922,-122.420870,12,24,1.143,15.857,1.058300,7.321222,1.174000,1.762,3.547,95.43,6349,9.978544
87,DanceJam,San Francisco,USA,37.781557,-122.407959,12,24,0.548,18.404,0.466333,6.389200,0.670000,0.539,2.387,95.43,6349,9.973720
173,Vibeex,Paris,FRA,48.856667,2.350987,4,2,0.293,0.194,0.878778,1.172667,2.073286,0.035,0.093,70.75,2511,9.960159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Verismo Networks,Mountain View,USA,37.387434,-122.051793,1,2,1.928,39.023,6.268000,11.550200,3.695900,1.389,3.174,95.43,6349,7.940171
9,Veeple,Palo Alto,USA,37.421142,-122.101182,6,4,0.428,33.275,10.879250,10.756800,1.732500,0.264,2.606,95.43,6349,7.904025
142,PicksPal,Mountain View,USA,37.400470,-122.072981,1,2,0.615,36.661,7.848750,9.541300,3.034800,0.161,0.904,95.43,6349,7.901558
143,Raptr,Mountain View,USA,37.403840,-122.078080,1,2,0.129,36.075,9.042875,9.857300,2.972200,0.743,0.486,95.43,6349,7.809534
140,PeerMe,Mountain View,USA,37.419819,-122.090188,1,2,0.997,34.109,10.682250,10.375000,1.963700,1.169,1.769,95.43,6349,7.732272